routes/web.php
<?php

use App\Http\Controllers\Auth\LoginController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BukuController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\UlasanController;
use App\Http\Controllers\KategoriController;
use App\Http\Controllers\NotFoundController;
use App\Http\Controllers\PeminjamanController;
use App\Http\Controllers\ReservationController;
use App\Http\Controllers\PengembalianController;
use App\Http\Controllers\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Auth::routes();

// Route::get('/', function () {
//     return view('login');
// });
Route::get('/', function () {
    return view('auth.login');
});

Route::middleware('auth')->group(function () {
    Route::resources([
        'books' => BukuController::class,
        'category' => KategoriController::class,
        'peminjaman' => PeminjamanController::class,
        'pengembalian' => PengembalianController::class,
        'reservasi' => ReservationController::class,
        'ulasan' => UlasanController::class,
    ]);
    Route::get('/back/{id}', [PengembalianController:: class, 'returnBooks'])->name('return.back')->middleware('role:admin');
    Route::post('/back/{id}', [PengembalianController:: class, 'insertRecord'])->name('return.insert')->middleware('role:admin');
    Route::get('/back', [PengembalianController:: class, 'index'])->name('return.index')->middleware('role:admin');
    Route::get('/home', [HomeController::class, 'index'])->name('home');
    Route::get('/404', [NotFoundController::class, 'index'])->name('404')->middleware('role:admin');
    Route::get('/user/{username}/{id}',[UserController::class, 'index'])->name('user.index')->middleware('role:admin');
    Route::put('/user/{username}/{id}',[UserController::class, 'update'])->name('user.update')->middleware('role:admin');
});

resources/views/books/view-books.blade.php
@section('title', 'Halaman Buku')
@section('breadcumb-title', 'Daftar Buku')
@extends('template.index')
@section('content')
    <div class="row">
        <div class="col-md-12">
            @if ($message = Session::get('success'))
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <strong>{{ $message }}</strong>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            @endif
            <div class="card">
                <div class="card-header">
                    <a class="btn btn-info btn-sm" href="{{ route('books.create') }}"><i class="fas fa-plus-circle"></i> Tambah
                        buku</a>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Photo</th>
                                <th>Kategori</th>
                                <th>Judul</th>
                                <th>Pengarang</th>
                                <th>Penerbit</th>
                                <th>Th.Terbit</th>
                                <th>Harga Sewa</th>
                                <th>Stok</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($buku as $rows)
                            <tr>
                                <td class="align-middle">{{ $loop->iteration }}</td>
                                <td class="align-middle"><img width="80" height="80" class="img-thumbnail" src="{{asset('assets/image/'.$rows->photo)}}" alt=""></td>
                                <td class="align-middle">{{ $rows->Kategori->nama }}</td>
                                <td class="align-middle">{{ $rows->judul }}</td>
                                <td class="align-middle">{{ $rows->pengarang }}</td>
                                <td class="align-middle">{{ $rows->penerbit }}</td>
                                <td class="align-middle">{{ $rows->tahun_terbit }}</td>
                                <td class="align-middle">{{ 'Rp. '.number_format($rows->harga,0, ',','.') }}</td>
                                <td class="align-middle">{{ $rows->stok_buku }}</td>
                                <td class="align-middle">
                                    <div class="btn-group dropleft">
                                        <button type="button" class="btn btn-primary dropdown-toggle"
                                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            <i class="fas fa-eye"></i>
                                        </button>
                                        <div class="dropdown-menu bg-light">
                                            <a class="dropdown-item" href="{{route('books.edit', $rows->id_buku)}}"><i class="fas fa-edit" ></i> Ubah</a>
                                            <form method="POST" action="{{route('books.destroy', $rows->id_buku)}}">
                                                @csrf
                                                @method('DELETE')
                                                <button type="submit" class="dropdown-item"><i class="fas fa-trash" ></i> Hapus</button>
                                            </form>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/books/view-kategori.blade.php
@section('title', 'Halaman Category')
@section('breadcumb-title', 'Kategori Buku')
@extends('template.index')
@section('content')
    <div class="row">
        <div class="col-md-12">
            @if ($message = Session::get('success'))
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <strong>{{ $message }}</strong>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            @endif
            <div class="card">
                <div class="card-header">
                    <a class="btn btn-info btn-sm" href="{{ route('category.create') }}"><i class="fas fa-plus-circle"></i>
                        Tambah Kategori</a>
                </div>
                <div class="card-body">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Nama</th>
                                <th>Deskripsi</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($kategori as $data)
                                <tr>
                                    <td>{{ $loop->iteration }}</td>
                                    <td>{{ $data->nama }}</td>
                                    <td>{{ $data->deskripsi }}</td>
                                    <td>
                                        <div class="btn-group dropleft">
                                            <button type="button" class="btn btn-primary dropdown-toggle"
                                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                <i class="fas fa-eye"></i>
                                            </button>
                                            <div class="dropdown-menu bg-light">
                                                <a class="dropdown-item"  href="{{ route('category.edit' ,$data->id_kategori) }}"><i class="fas fa-edit" ></i> Ubah</a>
                                                <a onclick="event.preventDefault();
                                                document.getElementById('delete-category').submit()" class="dropdown-item" href="{{ route('category.destroy',$data->id_kategori) }}"><i class="fas fa-trash" ></i> Delete</a>
                                                <form id="delete-category" action="{{ route('category.destroy',$data->id_kategori) }}" role="form" method="post">
                                                    @csrf
                                                    @method('DELETE')
                                                </form>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection