routes/web.php
<?php

use App\Http\Controllers\Auth\LoginController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BukuController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\UlasanController;
use App\Http\Controllers\KategoriController;
use App\Http\Controllers\NotFoundController;
use App\Http\Controllers\PeminjamanController;
use App\Http\Controllers\ReservationController;
use App\Http\Controllers\PengembalianController;
use App\Http\Controllers\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Auth::routes();

// Route::get('/', function () {
//     return view('login');
// });
Route::get('/', function () {
    return view('auth.login');
});

Route::middleware('auth')->group(function () {
    Route::resources([
        'books' => BukuController::class,
        'category' => KategoriController::class,
        'peminjaman' => PeminjamanController::class,
        'pengembalian' => PengembalianController::class,
        'reservasi' => ReservationController::class,
        'ulasan' => UlasanController::class,
    ]);
    Route::get('/back/{id}', [PengembalianController:: class, 'returnBooks'])->name('return.back')->middleware('role:admin');
    Route::post('/back/{id}', [PengembalianController:: class, 'insertRecord'])->name('return.insert')->middleware('role:admin');
    Route::get('/back', [PengembalianController:: class, 'index'])->name('return.index')->middleware('role:admin');
    Route::get('/home', [HomeController::class, 'index'])->name('home');
    Route::get('/404', [NotFoundController::class, 'index'])->name('404')->middleware('role:admin');
    Route::get('/user/{username}/{id}',[UserController::class, 'index'])->name('user.index')->middleware('role:admin');
    Route::put('/user/{username}/{id}',[UserController::class, 'update'])->name('user.update')->middleware('role:admin');
});

resources/views/template/breadcumb.blade.php
<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 class="m-0 text-dark">@yield('breadcumb-title')</h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item active">@yield('breadcumb-title')</li>
          </ol>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>
  <!-- /.content-header -->

resources/views/template/footer.blade.php
<script src="{{ asset('assets/plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<script src="{{ asset('assets/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js') }}"></script>

<script src="{{ asset('assets/plugins/jquery-mousewheel/jquery.mousewheel.js') }}"></script>
<script src="{{ asset('assets/plugins/raphael/raphael.min.js') }}"></script>
<script src="{{ asset('assets/plugins/jquery-mapael/jquery.mapael.min.js') }}"></script>
<script src="{{ asset('assets/plugins/jquery-mapael/maps/usa_states.min.js') }}"></script>
<script src="{{ asset('assets/plugins/chart.js/Chart.min.js') }}"></script>
<script src="{{ asset('assets/dist/js/pages/dashboard2.js') }}"></script>
<script src="{{ asset('assets/plugins/select2/js/select2.full.min.js') }}"></script>
<script src="{{ asset('assets/plugins/bootstrap4-duallistbox/jquery.bootstrap-duallistbox.min.js') }}"></script>

<script src="{{ asset('assets/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables-responsive/js/dataTables.responsive.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables-responsive/js/responsive.bootstrap4.min.js') }}"></script>
{{-- <script src="{{ asset('assets/plugins/moment/locales.min.js') }}"></script>
<script src="{{ asset('assets/plugins/moment/moment-with-locales.js') }}"></script> --}}
<script src="{{ asset('assets/dist/js/adminlte.js') }}"></script>
<script src="{{ asset('assets/dist/js/demo.js') }}"></script>
<script>
    $(function() {
        $("#example1").DataTable({
            "responsive": true,
            "autoWidth": false,
        });
        $('#example2').DataTable({
            "paging": true,
            "lengthChange": false,
            "searching": false,
            "ordering": true,
            "info": true,
            "autoWidth": false,
            "responsive": true,
        });

        //Initialize Select2 Elements
        $('.select2').select2()

        //Initialize Select2 Elements
        $('.select2bs4').select2({
            theme: 'bootstrap4'
        })

        //Datemask dd/mm/yyyy
        $('#datemask').inputmask('dd/mm/yyyy', {
            'placeholder': 'dd/mm/yyyy'
        })
        //Datemask2 mm/dd/yyyy
        $('#datemask2').inputmask('mm/dd/yyyy', {
            'placeholder': 'mm/dd/yyyy'
        })
        //Money Euro
        $('[data-mask]').inputmask()

        //Date range picker
        $('#reservation').daterangepicker()
        //Date range picker with time picker
        $('#reservationtime').daterangepicker({
            timePicker: true,
            timePickerIncrement: 30,
            locale: {
                format: 'MM/DD/YYYY hh:mm A'
            }
        })
        //Date range as a button
        $('#daterange-btn').daterangepicker({
                ranges: {
                    'Today': [moment(), moment()],
                    'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
                    'Last 7 Days': [moment().subtract(6, 'days'), moment()],
                    'Last 30 Days': [moment().subtract(29, 'days'), moment()],
                    'This Month': [moment().startOf('month'), moment().endOf('month')],
                    'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1,
                        'month').endOf(
                        'month')]
                },
                startDate: moment().subtract(29, 'days'),
                endDate: moment()
            },
            function(start, end) {
                $('#reportrange span').html(start.format('MMMM D, YYYY') + ' - ' + end.format(
                    'MMMM D, YYYY'))
            }
        )

        //Timepicker
        $('#timepicker').datetimepicker({
            format: 'LT'
        })

        //Bootstrap Duallistbox
        $('.duallistbox').bootstrapDualListbox()

        //Colorpicker
        $('.my-colorpicker1').colorpicker()
        //color picker with addon
        $('.my-colorpicker2').colorpicker()

        $('.my-colorpicker2').on('colorpickerChange', function(event) {
            $('.my-colorpicker2 .fa-square').css('color', event.color.toString());
        });

        $("input[data-bootstrap-switch]").each(function() {
            $(this).bootstrapSwitch('state', $(this).prop('checked'));
        });
    });
</script>

<script>
    $(document).ready(function() {
        $("#addbtn").click(function(e) {
            e.preventDefault();
            alert();
        });

        $("#photo").change(function (e) {
            e.preventDefault();
            let file = e.target.files[0];
            if(file){
              let reader = new FileReader();
              reader.onload = function(data){
                $("#preview").attr("src",data.target.result);
              }
              reader.readAsDataURL(file);
            }
            $(this).appendTo("#path-photo");
        });

        $("#show_pass").click(function (e) {
            e.preventDefault();
            $(this).css('cursor', 'pointer')
            let password = $("#password").prop('type');
            if(password == 'password'){
                $("#password").prop('type', 'text');
                $(this).removeClass('fas fa-eye').addClass('fas fa-eye-slash')
            }else{
                $("#password").prop('type', 'password');
                $(this).removeClass('fas fa-eye-slash').addClass('fas fa-eye')
            }
        });

        function realTimeHarga(){
            let harga = $("#buku option:selected").data('harga')
            $("#hargasewa").val(harga);
            console.log(harga);
        }
        $("#buku").change(function (e) {
            e.preventDefault();
            realTimeHarga()
        });
        // moment.locale('en');
        // let tgl_sekarang = moment().format('Y-MM-D');
        // let tgl_kembali = $("#tgl_kembali").text();
        // if(tgl_kembali < tgl_sekarang ){
        //     console.log("Benar");
        // }else{
        //     console.log("Salah");

        // }


    });

</script>

</body>

</html>

resources/views/template/header.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="shortcut icon" href="{{ asset('assets/icon/icon.jpg') }}" type="image/x-icon">
    <link rel="stylesheet" href="{{ asset('assets/plugins/fontawesome-free/css/all.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/plugins/overlayScrollbars/css/OverlayScrollbars.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/plugins/select2/css/select2.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/plugins/datatables-responsive/css/responsive.bootstrap4.min.css') }}">
    <!-- Select2 -->
    <link rel="stylesheet" href="{{ asset('assets/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css') }}">
    <!-- Bootstrap4 Duallistbox -->
    <link rel="stylesheet" href="{{ asset('assets/plugins/bootstrap4-duallistbox/bootstrap-duallistbox.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/dist/css/adminlte.min.css') }}">
    <script src="{{ asset('assets/plugins/jquery/jquery.min.js') }}"></script>
    <title>@yield('title')</title>
    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.bunny.net">
    <link href="https://fonts.bunny.net/css?family=figtree:400,600&display=swap" rel="stylesheet" />
    @vite(['resources/js/app.js'])
</head>

<body class="hold-transition sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixeds">

resources/views/template/index.blade.php
{{-- Parent Page --}}
@section('title', 'home')
@include('template.header')
<div class="wrapper">
    @include('template.navbar')
    @include('template.sidebar')
    <div class="content-wrapper">
        @include('template.breadcumb')
        <section class="content">
            <div class="container-fluid">
                @include('template.widget')
                {{-- all content in here --}}
                @yield('content')
            </div>
        </section>
    </div>
    <footer class="main-footer">
        <strong>Copyright &copy; 2014-2019 <a href="http://adminlte.io">AdminLTE.io</a>.</strong>
        All rights reserved.
        <div class="float-right d-none d-sm-inline-block">
            <b>Version</b> 3.0.4
        </div>
    </footer>
</div>
@include('template.footer')

resources/views/template/navbar.blade.php
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#" role="button">
            {{ "Hai, ".ucwords(Auth::user()->name) }}
        </a>
      </li>
    </ul>
  </nav>

resources/views/template/sidebar.blade.php
<style>
    .user-panel img {
      height: 2.1rem;
      width: 2.1rem;
      max-width: 2.1rem;
      max-height: 2.1rem;

  }
  .nav-sidebar .nav-header:not(:first-of-type) {
      padding: .5rem .5rem .5rem;
  }
  </style>
 <!-- Main Sidebar Container -->
 <aside class="main-sidebar sidebar-dark-primary elevation-4">
     <!-- Brand Logo -->
     <a href="#" class="brand-link">
         <img src="{{ asset('assets/icon/icon.jpg') }}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
         <span class="brand-text font-weight-light">BacaPintar</span>
     </a>

     <!-- Sidebar -->
     <div class="sidebar">
         <!-- Sidebar user panel (optional) -->
         <div class="user-panel mt-3 pb-3 mb-3 d-flex">
             <div class="image">
                 <img src="{{ asset('assets/image/'.Auth::user()->avatar) }}" class="img-circle elevation-2" alt="User Image">
             </div>
             <div class="info">
                 <a href="{{ route('user.index',['username'=>Auth::user()->username, 'id'=>Auth::user()->id_user]) }}" class="d-block">{{ ucwords(Auth::user()->name) }}</a>
             </div>
         </div>

         <!-- Sidebar Menu -->
         <nav class="mt-2">
             <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
                 data-accordion="false">
                 <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
                 <li class="nav-item">
                     <a href="{{ route('home') }}" class="nav-link">
                         <i class="nav-icon fas fa-tachometer-alt"></i>
                         <p>
                             Dashboard
                         </p>
                     </a>
                 </li>
                 <li class="nav-item has-treeview
                 @if (request()->is('category') || request()->is('books'))
                 menu-open
                 @endif
                 ">
                     <a href="#" class="nav-link
                        @if (request()->is('books') || request()->is('category'))
                        active
                        @endif
                        ">
                         <i class="nav-icon fas fa-book"></i>
                         <p>
                             Buku
                             <i class="fas fa-angle-left right"></i>
                             <span class="badge badge-info right">2</span>
                         </p>
                     </a>
                     <ul class="nav nav-treeview">
                         <li class="nav-item">
                             <a href="{{ route('category.index') }}" class="nav-link {{ request()->is('category') ? 'active' : '' }}">
                                 <i class="far fa-circle nav-icon"></i>
                                 <p>Kategori Buku</p>
                             </a>
                         </li>
                         <li class="nav-item">
                             <a href="{{ route('books.index') }}" class="nav-link {{ request()->is('books') ? 'active' : '' }}">
                                 <i class="far fa-circle nav-icon"></i>
                                 <p>Daftar Buku</p>
                             </a>
                         </li>
                     </ul>
                 </li>

                 <li class="nav-item has-treeview
                 @if (request()->is('peminjaman') || request()->is('back'))
                 menu-open
                 @endif">
                     <a href="#" class="nav-link @if (request()->is('peminjaman') || request()->is('back'))
                        active
                        @endif">
                         <i class="nav-icon fas fa-file-invoice-dollar"></i>
                         <p>
                             Transaksi
                             <i class="right fas fa-angle-left"></i>
                             <span class="badge badge-info right">2</span>
                         </p>
                     </a>
                     <ul class="nav nav-treeview">
                         <li class="nav-item">
                             <a href="{{ route('peminjaman.index') }}" class="nav-link {{ request()->is('peminjaman') ? 'active' : '' }}">
                                 <i class="far fa-circle nav-icon"></i>
                                 <p>Peminjaman</p>
                             </a>
                         </li>
                         <li class="nav-item">
                             <a href="{{ route('return.index') }}" class="nav-link {{ request()->is('back') ? 'active' : '' }}">
                                 <i class="far fa-circle nav-icon"></i>
                                 <p>Pengembalian Buku</p>
                             </a>
                         </li>
                     </ul>
                 </li>

                 <li class="nav-item">
                     <a href="{{ route('ulasan.index') }}" class="nav-link {{ request()->is('ulasan') ? 'active' : '' }}">
                         <i class="nav-icon fas fa-star"></i>
                         <p>
                             Ulasan
                         </p>
                     </a>
                 </li>


                 <li class="nav-header">SETTINGS</li>
                 <li class="nav-item">
                     <a href="#" class="nav-link">
                         <i class="nav-icon fas fa-user-cog"></i>
                         <p>
                             Akun
                         </p>
                     </a>
                 </li>

                 <li class="nav-item">
                     <a onclick="event.preventDefault();
                     document.getElementById('logout-form').submit();"
                         href="{{ route('logout') }}" class="nav-link">
                         <i class="nav-icon fas fa-sign-out-alt "></i>
                         <p>
                             Keluar
                         </p>
                     </a>
                     <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                        @csrf
                    </form>
                 </li>
             </ul>
         </nav>
     </div>
 </aside>

resources/views/template/widget.blade.php
<div class="row">
    <div class="col-12 col-sm-6 col-md-3">
      <div class="info-box">
        <span class="info-box-icon bg-info elevation-1"><i class="fas fa-user"></i></span>

        <div class="info-box-content">
          <span class="info-box-text">All User</span>
          <span class="info-box-number">
            {{ App\Models\User::count() }}
          </span>
        </div>
        <!-- /.info-box-content -->
      </div>
      <!-- /.info-box -->
    </div>
    <!-- /.col -->
    <div class="col-12 col-sm-6 col-md-3">
      <div class="info-box mb-3">
        <span class="info-box-icon bg-danger elevation-1"><i class="fas fa-book"></i></span>

        <div class="info-box-content">
          <span class="info-box-text">Data Buku</span>
          <span class="info-box-number">{{ App\Models\BukuModel::count() }}</span>
        </div>
        <!-- /.info-box-content -->
      </div>
      <!-- /.info-box -->
    </div>
    <!-- /.col -->

    <!-- fix for small devices only -->
    <div class="clearfix hidden-md-up"></div>

    <div class="col-12 col-sm-6 col-md-3">
      <div class="info-box mb-3">
        <span class="info-box-icon bg-success elevation-1"><i class="fas fa-dollar-sign"></i></span>

        <div class="info-box-content">
          <span class="info-box-text">Transaksi</span>
          <span class="info-box-number">{{ App\Models\PeminjamanModel::count() }}</span>
        </div>
        <!-- /.info-box-content -->
      </div>
      <!-- /.info-box -->
    </div>
    <!-- /.col -->
    <div class="col-12 col-sm-6 col-md-3">
      <div class="info-box mb-3">
        <span class="info-box-icon bg-warning elevation-1"><i class="fas fa-star"></i></span>

        <div class="info-box-content">
          <span class="info-box-text">Ulasan</span>
          <span class="info-box-number">{{ App\Models\UlasanModel::count() }}</span>
        </div>
        <!-- /.info-box-content -->
      </div>
      <!-- /.info-box -->
    </div>
    <!-- /.col -->
  </div>